-- ==========================================================
-- SCRIPT: REINICIO, ESTRUCTURA Y DATOS DE PRUEBA
-- MOTOR: ORACLE DATABASE (PL/SQL)
-- PREFIJO ESTUDIANTES: KLS_
-- ==========================================================

-- 1. ELIMINAR TABLAS (Ignora los errores si es la primera vez que lo corres)
DROP TABLE KLS_RECETA_ALIMENTO CASCADE CONSTRAINTS;
DROP TABLE KLS_RECETAS CASCADE CONSTRAINTS;
DROP TABLE KLS_USUARIOS CASCADE CONSTRAINTS;
DROP TABLE KLS_ALIMENTOS CASCADE CONSTRAINTS;
DROP TABLE KLS_AUDITORIA CASCADE CONSTRAINTS;

-- ==========================================================

-- 2. CREAR TABLAS

CREATE TABLE KLS_USUARIOS (
    id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'usuario'
);

CREATE TABLE KLS_ALIMENTOS (
    id_alimento NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    tipo VARCHAR2(20) CHECK (tipo IN ('Fruta', 'Verdura')),
    calorias NUMBER,
    temporada VARCHAR2(50)
);

CREATE TABLE KLS_RECETAS (
    id_receta NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200) NOT NULL,
    preparacion CLOB NOT NULL,
    id_usuario NUMBER,
    CONSTRAINT fk_recetas_usuario FOREIGN KEY (id_usuario) 
        REFERENCES KLS_USUARIOS (id_usuario) ON DELETE CASCADE
);

CREATE TABLE KLS_RECETA_ALIMENTO (
    id_receta_alimento NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_receta NUMBER NOT NULL,
    id_alimento NUMBER NOT NULL,
    cantidad VARCHAR2(50),
    CONSTRAINT fk_ra_receta FOREIGN KEY (id_receta) 
        REFERENCES KLS_RECETAS (id_receta) ON DELETE CASCADE,
    CONSTRAINT fk_ra_alimento FOREIGN KEY (id_alimento) 
        REFERENCES KLS_ALIMENTOS (id_alimento) ON DELETE CASCADE
);

CREATE TABLE KLS_AUDITORIA (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR2(50) NOT NULL,
    operacion VARCHAR2(10) NOT NULL,
    usuario_bd VARCHAR2(50) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datos_anteriores VARCHAR2(4000),
    datos_nuevos VARCHAR2(4000)
);

-- ==========================================================

-- 3. INSERTAR DATOS DE PRUEBA (Para que el Login y Dashboard funcionen)

-- Usuario Administrador
INSERT INTO KLS_USUARIOS (nombre, email, password, rol) 
VALUES ('Administrador', 'admin@correo.com', 'admin123', 'admin');

-- Usuario normal
INSERT INTO KLS_USUARIOS (nombre, email, password, rol) 
VALUES ('Dulce', 'dulce@correo.com', '123456', 'usuario');

-- Alimentos (Verduras)
INSERT INTO KLS_ALIMENTOS (nombre, tipo, calorias, temporada) VALUES ('Espinaca', 'Verdura', 23, 'Invierno - Primavera');
INSERT INTO KLS_ALIMENTOS (nombre, tipo, calorias, temporada) VALUES ('Zanahoria', 'Verdura', 41, 'Todo el año');
INSERT INTO KLS_ALIMENTOS (nombre, tipo, calorias, temporada) VALUES ('Brócoli', 'Verdura', 34, 'Otoño - Primavera');
INSERT INTO KLS_ALIMENTOS (nombre, tipo, calorias, temporada) VALUES ('Tomate', 'Verdura', 18, 'Verano');

-- Alimentos (Frutas)
INSERT INTO KLS_ALIMENTOS (nombre, tipo, calorias, temporada) VALUES ('Fresa', 'Fruta', 32, 'Mar - May');
INSERT INTO KLS_ALIMENTOS (nombre, tipo, calorias, temporada) VALUES ('Naranja', 'Fruta', 47, 'Nov - Abr');
INSERT INTO KLS_ALIMENTOS (nombre, tipo, calorias, temporada) VALUES ('Kiwi', 'Fruta', 61, 'Ene - Abr');

COMMIT;

-- ==========================================================
-- 4. TRIGGERS DE AUDITORÍA (PL/SQL)
-- ==========================================================

CREATE OR REPLACE TRIGGER TRG_AUDIT_ALIMENTOS
AFTER INSERT OR UPDATE OR DELETE ON KLS_ALIMENTOS
FOR EACH ROW
DECLARE
    v_operacion VARCHAR2(10);
    v_datos_ant VARCHAR2(4000);
    v_datos_nue VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_operacion := 'INSERT';
        v_datos_nue := 'ID: ' || :NEW.id_alimento || ', Nombre: ' || :NEW.nombre || ', Tipo: ' || :NEW.tipo;
    ELSIF UPDATING THEN
        v_operacion := 'UPDATE';
        v_datos_ant := 'ID: ' || :OLD.id_alimento || ', Nombre: ' || :OLD.nombre || ', Tipo: ' || :OLD.tipo;
        v_datos_nue := 'ID: ' || :NEW.id_alimento || ', Nombre: ' || :NEW.nombre || ', Tipo: ' || :NEW.tipo;
    ELSIF DELETING THEN
        v_operacion := 'DELETE';
        v_datos_ant := 'ID: ' || :OLD.id_alimento || ', Nombre: ' || :OLD.nombre || ', Tipo: ' || :OLD.tipo;
    END IF;

    INSERT INTO KLS_AUDITORIA (tabla_afectada, operacion, usuario_bd, datos_anteriores, datos_nuevos)
    VALUES ('KLS_ALIMENTOS', v_operacion, USER, v_datos_ant, v_datos_nue);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_USUARIOS
AFTER INSERT OR UPDATE OR DELETE ON KLS_USUARIOS
FOR EACH ROW
DECLARE
    v_operacion VARCHAR2(10);
    v_datos_ant VARCHAR2(4000);
    v_datos_nue VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_operacion := 'INSERT';
        v_datos_nue := 'ID: ' || :NEW.id_usuario || ', Nombre: ' || :NEW.nombre || ', Rol: ' || :NEW.rol;
    ELSIF UPDATING THEN
        v_operacion := 'UPDATE';
        v_datos_ant := 'ID: ' || :OLD.id_usuario || ', Nombre: ' || :OLD.nombre || ', Rol: ' || :OLD.rol;
        v_datos_nue := 'ID: ' || :NEW.id_usuario || ', Nombre: ' || :NEW.nombre || ', Rol: ' || :NEW.rol;
    ELSIF DELETING THEN
        v_operacion := 'DELETE';
        v_datos_ant := 'ID: ' || :OLD.id_usuario || ', Nombre: ' || :OLD.nombre || ', Rol: ' || :OLD.rol;
    END IF;

    INSERT INTO KLS_AUDITORIA (tabla_afectada, operacion, usuario_bd, datos_anteriores, datos_nuevos)
    VALUES ('KLS_USUARIOS', v_operacion, USER, v_datos_ant, v_datos_nue);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_RECETAS
AFTER INSERT OR UPDATE OR DELETE ON KLS_RECETAS
FOR EACH ROW
DECLARE
    v_operacion VARCHAR2(10);
    v_datos_ant VARCHAR2(4000);
    v_datos_nue VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_operacion := 'INSERT';
        v_datos_nue := 'ID: ' || :NEW.id_receta || ', Titulo: ' || :NEW.titulo;
    ELSIF UPDATING THEN
        v_operacion := 'UPDATE';
        v_datos_ant := 'ID: ' || :OLD.id_receta || ', Titulo: ' || :OLD.titulo;
        v_datos_nue := 'ID: ' || :NEW.id_receta || ', Titulo: ' || :NEW.titulo;
    ELSIF DELETING THEN
        v_operacion := 'DELETE';
        v_datos_ant := 'ID: ' || :OLD.id_receta || ', Titulo: ' || :OLD.titulo;
    END IF;

    INSERT INTO KLS_AUDITORIA (tabla_afectada, operacion, usuario_bd, datos_anteriores, datos_nuevos)
    VALUES ('KLS_RECETAS', v_operacion, USER, v_datos_ant, v_datos_nue);
END;
/
