-- ==========================================================
-- SCRIPT: ESTRUCTURA (SOLO TABLAS Y RELACIONES)
-- MOTOR: ORACLE DATABASE (PL/SQL)
-- PREFIJO ESTUDIANTES: KLS_
-- ==========================================================

-- 1. Eliminar tablas si existen (para evitar errores en ejecuciones múltiples)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE KLS_RECETA_ALIMENTO CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE KLS_RECETAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE KLS_USUARIOS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE KLS_ALIMENTOS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE KLS_AUDITORIA CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- 2. Crear Tabla de Usuarios
CREATE TABLE KLS_USUARIOS (
    id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'usuario'
);

-- 3. Crear Tabla de Alimentos (Frutas y Verduras)
CREATE TABLE KLS_ALIMENTOS (
    id_alimento NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    tipo VARCHAR2(20) CHECK (tipo IN ('Fruta', 'Verdura')),
    calorias NUMBER,
    temporada VARCHAR2(50)
);

-- 4. Crear Tabla de Recetas
CREATE TABLE KLS_RECETAS (
    id_receta NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200) NOT NULL,
    preparacion CLOB NOT NULL,
    id_usuario NUMBER,
    CONSTRAINT fk_recetas_usuario FOREIGN KEY (id_usuario) 
        REFERENCES KLS_USUARIOS (id_usuario) ON DELETE CASCADE
);

-- 5. Crear Tabla Intermedia: Recetas y Alimentos (Muchos a Muchos)
CREATE TABLE KLS_RECETA_ALIMENTO (
    id_receta_alimento NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_receta NUMBER NOT NULL,
    id_alimento NUMBER NOT NULL,
    cantidad VARCHAR2(50),
    CONSTRAINT fk_ra_receta FOREIGN KEY (id_receta) 
        REFERENCES KLS_RECETAS (id_receta) ON DELETE CASCADE,
    CONSTRAINT fk_ra_alimento FOREIGN KEY (id_alimento) 
        REFERENCES KLS_ALIMENTOS (id_alimento) ON DELETE CASCADE
);

-- 6. Crear Tabla de Auditoría (Para Fase 3)
CREATE TABLE KLS_AUDITORIA (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR2(50) NOT NULL,
    operacion VARCHAR2(10) NOT NULL,
    usuario_bd VARCHAR2(50) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datos_anteriores VARCHAR2(4000),
    datos_nuevos VARCHAR2(4000)
);

COMMIT;