-- ==========================================================
-- SCRIPT: BACKUP COMPLETO (ESTRUCTURA + DATOS)
-- MOTOR: ORACLE DATABASE (PL/SQL)
-- PREFIJO ESTUDIANTES: KLS_
-- ==========================================================

-- ==========================================
-- SECCIÓN 1: ESTRUCTURA (DDL)
-- ==========================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE KLS_RECETA_ALIMENTO CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE KLS_RECETAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE KLS_USUARIOS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE KLS_ALIMENTOS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE KLS_AUDITORIA CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE KLS_USUARIOS (
    id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'usuario'
);

CREATE TABLE KLS_ALIMENTOS (
    id_alimento NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    tipo VARCHAR2(20) CHECK (tipo IN ('Fruta', 'Verdura')),
    calorias NUMBER,
    temporada VARCHAR2(50)
);

CREATE TABLE KLS_RECETAS (
    id_receta NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200) NOT NULL,
    preparacion CLOB NOT NULL,
    id_usuario NUMBER,
    CONSTRAINT fk_recetas_usuario FOREIGN KEY (id_usuario) 
        REFERENCES KLS_USUARIOS (id_usuario) ON DELETE CASCADE
);

CREATE TABLE KLS_RECETA_ALIMENTO (
    id_receta_alimento NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_receta NUMBER NOT NULL,
    id_alimento NUMBER NOT NULL,
    cantidad VARCHAR2(50),
    CONSTRAINT fk_ra_receta FOREIGN KEY (id_receta) 
        REFERENCES KLS_RECETAS (id_receta) ON DELETE CASCADE,
    CONSTRAINT fk_ra_alimento FOREIGN KEY (id_alimento) 
        REFERENCES KLS_ALIMENTOS (id_alimento) ON DELETE CASCADE
);

CREATE TABLE KLS_AUDITORIA (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR2(50) NOT NULL,
    operacion VARCHAR2(10) NOT NULL,
    usuario_bd VARCHAR2(50) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    datos_anteriores VARCHAR2(4000),
    datos_nuevos VARCHAR2(4000)
);

-- ==========================================
-- SECCIÓN 2: INSERCIÓN DE DATOS (DML)
-- ==========================================

-- Usuarios Base
INSERT INTO KLS_USUARIOS (nombre, email, password, rol) VALUES ('Admin Principal', 'admin@sistema.com', 'admin123', 'administrador');
INSERT INTO KLS_USUARIOS (nombre, email, password, rol) VALUES ('Juan Perez', 'juan@gmail.com', 'pass123', 'usuario');
INSERT INTO KLS_USUARIOS (nombre, email, password, rol) VALUES ('Maria Rodriguez', 'maria@hotmail.com', 'pass456', 'usuario');

-- Alimentos
INSERT INTO KLS_ALIMENTOS (nombre, tipo, calorias, temporada) VALUES ('Manzana', 'Fruta', 52, 'Otoño');
INSERT INTO KLS_ALIMENTOS (nombre, tipo, calorias, temporada) VALUES ('Plátano', 'Fruta', 89, 'Todo el año');
INSERT INTO KLS_ALIMENTOS (nombre, tipo, calorias, temporada) VALUES ('Zanahoria', 'Verdura', 41, 'Primavera');
INSERT INTO KLS_ALIMENTOS (nombre, tipo, calorias, temporada) VALUES ('Brócoli', 'Verdura', 34, 'Invierno');

-- Recetas
INSERT INTO KLS_RECETAS (titulo, preparacion, id_usuario) VALUES ('Ensalada Fresca de Manzana', '1. Lavar la manzana y zanahoria. 2. Cortar en cubos y rallar. 3. Mezclar todo.', 2);
INSERT INTO KLS_RECETAS (titulo, preparacion, id_usuario) VALUES ('Crema de Brócoli', '1. Hervir brócoli. 2. Licuar con un poco de leche. 3. Calentar a fuego lento.', 3);

-- Relacionar Recetas con Ingredientes (N:M)
-- Ensalada Fresca de Manzana: Usa Manzana y Zanahoria
INSERT INTO KLS_RECETA_ALIMENTO (id_receta, id_alimento, cantidad) VALUES (1, 1, '2 unidades');
INSERT INTO KLS_RECETA_ALIMENTO (id_receta, id_alimento, cantidad) VALUES (1, 3, '1 unidad grande');

-- Crema de Brócoli: Usa Brócoli
INSERT INTO KLS_RECETA_ALIMENTO (id_receta, id_alimento, cantidad) VALUES (2, 4, '500 gramos');

COMMIT;